### ISSUE TITLE
Resource isn't properly created on darwin target

### ISSUE THREAD

**Issue by ubuntudroid** [goncalossilva/kotlinx-resources#40]
In my `commonTest` module I have a `json` folder with a json5 file in it.

![CleanShot 2023-02-17 at 13 59 15](https://user-images.githubusercontent.com/519867/219659391-75567567-70e4-4178-a50d-508e60aee0ae.png)

I'm using this file in my tests like so:

```kotlin
val resource = Resource("src/commonTest/json/Meals.json5")
assertTrue { resource.exists() }
...
```

This works perfectly fine on the JVM, but not at all on darwin. On the latter, I'm getting a `RuntimeException` when trying to call `readText()` and `exists()` returns `false`.

Any idea what I might be doing wrong?

**Comment by goncalossilva** [comment]
Thanks for the report, @ubuntudroid! That's unexpected. It seems [no path is found](https://github.com/goncalossilva/kotlinx-resources/blob/5705f5cf293ae173fded59aaf7df22f20488b6b0/resources-library/src/darwinMain/kotlin/Resource.kt#L9-L12) for the resource. That would mean the plugin isn't running, or failed to move the resource.

1. Can you confirm you're using the plugin, alongside the library?
2. When you list the tasks for the projects, which ones do you see starting with `copyResources`?
3. Which Gradle version are you using? And Kotlin version?

**Comment by ubuntudroid** [comment]
1. Yes, and it works fine on Android (but maybe the plugin is just needed for iOS?). In my shared `build.gradle.kts`:
```kts
plugins {
    alias(libs.plugins.goncalossilva.test.resources)
}
```
... and my `libs.versions.toml`:
```toml
[versions]
test-resources = "0.2.4"

[libraries]
goncalossilva-test-resources = { module = "com.goncalossilva:resources", version.ref = "test-resources" }

[plugins]
goncalossilva-test-resources = { id = "com.goncalossilva.resources", version.ref = "test-resources" }
```
2. None, which probably isn't a good sign. 😅 
3. Gradle 8.0-rc-2, Kotlin 1.8.0

**Comment by goncalossilva** [comment]
Ha! I haven't done the work to update Gradle to 8.0, which may be related. I plan to look into this over the coming weeks (possibly after an 8.0.1 that usually comes). Could you try with Gradle 7.6?

**Comment by ubuntudroid** [comment]
Quickly tried to downgrade the project, but wasn't able to make its configuration work with Gradle 7.6 as this would have also meant downgrading AGP and there were quite a few changes between AGP 7.4.1 and 8.0.0-beta03...

Guess I'll then just have to wait for your next update. Let me know when you need me to test it in my project. Thanks for your efforts! 🙏

**Comment by goncalossilva** [comment]
0.2.5 is out, and it should resolve this issue. Can you check it out?

**Comment by ubuntudroid** [comment]
Many thanks for the quick update! 🙏 

Unfortunately the test still fails as the resource still doesn't seem to exist. 🤔

**Comment by ubuntudroid** [comment]
And also still no sign of any `copyResources` Gradle tasks...

**Comment by goncalossilva** [comment]
Ha, that's surprising. I've updated [kotlinx-murmurhash](https://github.com/goncalossilva/kotlinx-murmurhash) successfully after the recent changes. More questions if you don't mind:
- Could you review the project for any meaningful changes, compared to yours? Particularly, `build.gradle` and the way test resources are set.
- Does your project happen to be OSS? I'd be happy to take a look.

**Comment by ubuntudroid** [comment]
Alright, I checked the murmurhash project (loving the git-hook task there, btw! 🤩 ) and it looks quite similar to my setup. The project is an internal test project, but I've uploaded it to GitHub (ubuntudroid/mixer) and added you as a collaborator.

Many thanks for assisting me with this issue once again. 🙏

**Comment by goncalossilva** [comment]
Thanks for sharing the project, it was much easier to debug!

The issue is that the assets must be placed inside a [resources](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html#org.gradle.api.tasks.SourceSet:resources) folder. For instance, moving from `src/commonTest/json/Meals.json5` to `src/commonTest/resources/json/Meals.json5`. The discards source sets when no resources are found, which is the case. Updating the path locally has the test passing on the simulator.

**Comment by ubuntudroid** [comment]
Awesome, that works indeed! Thanks again for your support and this super helpful library! 🤗
